# Generated by Django 4.2.2 on 2025-12-23 04:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Введите дату и время окончания отправки",
                null=True,
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите Сообщение",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing_list_management.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Введите имя получателя рассылки",
                null=True,
                to="mailing_list_management.recipient",
                verbose_name="Имя получателя рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Введите дату и время начала отправки",
                null=True,
                verbose_name="Дата и время начала отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создана"),
                    ("RUNNING", "Запущена"),
                    ("COMPLETED", "Завершена"),
                ],
                default="CREATED",
                help_text="Введите статус",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(
                help_text="Введите тело письма",
                max_length=255,
                verbose_name="Тело письма",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(
                help_text="Введите тему письма",
                max_length=255,
                verbose_name="Тема письма",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Введите комментарий",
                max_length=55,
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(
                help_text="Введите свою электронную почту",
                max_length=254,
                unique=True,
                verbose_name="Эл. почта",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="name",
            field=models.CharField(
                help_text="Введите имя получателя рассылки",
                max_length=255,
                verbose_name="Имя получателя рассылки",
            ),
        ),
    ]
