# Generated by Django 4.2.2 on 2025-12-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing_list_management",
            "0002_alter_mailing_options_alter_message_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sendattempt",
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
    ]
