# Generated by Django 4.2.2 on 2025-12-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list_management", "0003_alter_sendattempt_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Введите имя получателя рассылки",
                to="mailing_list_management.recipient",
                verbose_name="Имя получателя рассылки",
            ),
        ),
    ]
